name: Despliegue Automático AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Sincronizar y Desplegar en AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            
            echo "1. Descargando código fresco desde GitHub..."
            # Creamos una carpeta totalmente nueva y limpia para evitar problemas de permisos
            if [ ! -d "/home/ubuntu/produccion-backend" ]; then
              git clone https://github.com/Dante22LA/sistema-voto-backend.git /home/ubuntu/produccion-backend
            fi
            
            cd /home/ubuntu/produccion-backend
            
            # Forzamos a que el servidor quede exactamente igual que tu GitHub
            git fetch --all
            git reset --hard origin/main
            
            echo "2. Reconstruyendo imagen Docker..."
            sudo docker build -t api-votacion .
            
            echo "3. Reiniciando el sistema..."
            sudo docker rm -f servidor-biometrico || true
            
            echo "4. Encendiendo con llaves maestras..."
            sudo docker run -d -p 8000:8000 -v /home/ubuntu/votacion.db:/app/votacion.db -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --name servidor-biometrico api-votacion
            
            echo "¡Despliegue completado con éxito!"